// Generated by CoffeeScript 1.7.1

/*
grunt-xmllint

Copyright (c) 2014 Andreas Lappe
http://zimmer7.com
Licensed under the BSD license.
 */

(function() {
  module.exports = function(grunt) {
    var xmllint;
    xmllint = (require('./lib/xmllint')).init(grunt);
    return grunt.registerMultiTask('xmllint', 'Run xmllint', function() {
      xmllint.setup(this);
      return xmllint.run();
    });
  };

}).call(this);
